name: Deployment to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main  # <-- specify the branch you want to deploy from
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # cache: 'npm'
          # cache-dependency-path: '**/package-lock.json'

      - run: npm ci
      - run: npm run build:production
      - run: hugo --baseURL https://kaukang.taigi.info --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }} # <-- specify same branch as above here
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # publish_branch: gh-pages # default: gh-pages
          cname: kaukang.taigi.info   # default: no custom domain
